import Navbar from "@/component/NavBar/Navbar";
import AuthProvider from "@/context/auth";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar/>
          header
          {children}
          Don't have an account?
        </AuthProvider>
      </body>
    </html>
  );
}
